# Generated by Django 4.0.4 on 2022-08-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='date_posted',
            new_name='blog_date_posted',
        ),
    ]
