# Generated by Django 4.0.4 on 2022-09-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_nftdetails_nftpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_welcome_intro', models.TextField(max_length=255)),
                ('about_nft', models.TextField(max_length=255)),
                ('more_about_nft', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='NftDetails',
        ),
        migrations.AlterField(
            model_name='nftpost',
            name='nft_type',
            field=models.CharField(choices=[('collections', 'collections'), ('single', 'single')], max_length=100),
        ),
    ]
