# Generated by Django 4.0.4 on 2022-09-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_nftdetail_delete_nftdetails_alter_nftpost_nft_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDetails',
            new_name='BlogDetail',
        ),
    ]
