# Generated by Django 4.0.4 on 2022-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_nftimages_alter_nftdetail_about_nft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftpost',
            name='nft_type',
            field=models.CharField(choices=[('collections', 'collections'), ('single', 'single')], max_length=100),
        ),
    ]
