# Generated by Django 4.0.4 on 2022-09-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_nftpost_nft_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NftImages',
            new_name='NftImage',
        ),
    ]
