# Generated by Django 4.0.4 on 2022-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_nftpost_nft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftpost',
            name='nft_fixed_price',
            field=models.IntegerField(default=0.01, max_length=100),
        ),
        migrations.AddField(
            model_name='nftpost',
            name='nft_old_price',
            field=models.IntegerField(default=0.01, max_length=100),
        ),
        migrations.AlterField(
            model_name='nftpost',
            name='nft_type',
            field=models.CharField(choices=[('single', 'single'), ('collections', 'collections')], max_length=100),
        ),
    ]
