# Generated by Django 4.0.4 on 2022-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_nftpost_nft_fixed_price_nftpost_nft_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftpost',
            name='nft_fixed_price',
            field=models.FloatField(default=0.01, max_length=100),
        ),
        migrations.AlterField(
            model_name='nftpost',
            name='nft_old_price',
            field=models.FloatField(default=0.01, max_length=100),
        ),
        migrations.AlterField(
            model_name='nftpost',
            name='nft_type',
            field=models.CharField(choices=[('collections', 'collections'), ('single', 'single')], max_length=100),
        ),
    ]
