# Generated by Django 4.0.4 on 2022-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_nftpost_nft_more_content_alter_nftpost_nft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftpost',
            name='nft_external_link',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nftpost',
            name='nft_type',
            field=models.CharField(choices=[('single', 'single'), ('collection', 'collection')], max_length=100),
        ),
    ]
