# Generated by Django 4.0.4 on 2022-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.CharField(max_length=100)),
                ('pic', models.ImageField(default='me.jpg', upload_to='myimage')),
            ],
        ),
    ]
