# Generated by Django 4.0.4 on 2022-08-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='service_files',
            field=models.FileField(default='marketing.mp4', upload_to='service_details_files'),
        ),
    ]
