# Generated by Django 4.0.4 on 2022-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_swirlinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='swirlinfo',
            name='whatsapp_link',
            field=models.URLField(default='link', max_length=255),
        ),
    ]
