# Generated by Django 4.0.4 on 2022-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_swirlinfo_whatsapp_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_content', models.TextField()),
                ('project_file', models.FileField(default='project.mp4', upload_to='project_medias')),
            ],
        ),
    ]
