# Generated by Django 4.0.4 on 2022-09-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projectpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='project_media',
            field=models.FileField(default='project.mp4', upload_to='project_medias'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='project_file',
            field=models.FileField(upload_to='project_files'),
        ),
    ]
