# Generated by Django 4.0.4 on 2022-09-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_projectpost_project_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swirlinfo',
            name='fiverr_link',
            field=models.URLField(default='link', max_length=255),
        ),
        migrations.AddField(
            model_name='swirlinfo',
            name='upwork_link',
            field=models.URLField(default='link', max_length=255),
        ),
    ]
